### ISSUE TITLE
ME resets custom shaders on males.

### ISSUE THREAD

**Issue by Electrognome** [IllusionMods/KK_Plugins#112] opened 2021-10-23 03:22 UTC
There is a bug in MaterialEditor. In studio, once I select male character and click "Status" window, custom shader that I selected in maker for the body resets to default one, every time. This affects only male chars for some reason, even if I drag and drop them to female creator. It only affects the body, not the face.

How to recreate:
Open male char creator, add some shader to the body and face (for example BetterMatCap).
Open up studio and load modified character.
Select the character and click "Status" in the anim menu.

**Comment by DeathWeasel1337** [comment] 2021-11-12 15:30
I believe this should be fixed if you have the latest version of both MaterialEditor and UncensorSelector, it was caused by US unnecessarily changing uncensors when clicking the status menu, and ME should now reapply changes whenever uncensors are changed as well.

**Closed by DeathWeasel1337** 2021-11-12 15:30 UTC
